-- CreateTable
CREATE TABLE `ota_releases` (
    `id` VARCHAR(191) NOT NULL,
    `layer` VARCHAR(191) NOT NULL,
    `platform` VARCHAR(191) NOT NULL,
    `bundleType` VARCHAR(191) NULL,
    `updateMethod` VARCHAR(191) NULL,
    `channel` VARCHAR(191) NOT NULL DEFAULT 'stable',
    `version` VARCHAR(191) NOT NULL,
    `buildNumber` INTEGER NOT NULL,
    `minBaseBuild` INTEGER NULL,
    `minBackendBuild` INTEGER NULL,
    `downloadUrl` TEXT NOT NULL,
    `feedUrl` TEXT NULL,
    `fileSize` BIGINT NOT NULL,
    `sha256` VARCHAR(191) NOT NULL,
    `signature` TEXT NULL,
    `releaseNotes` TEXT NULL,
    `forceUpdate` BOOLEAN NOT NULL DEFAULT false,
    `rolloutPercent` INTEGER NOT NULL DEFAULT 100,
    `rolloutRule` JSON NULL,
    `isPublished` BOOLEAN NOT NULL DEFAULT false,
    `publishedAt` DATETIME(3) NULL,
    `createdBy` VARCHAR(191) NULL,
    `deletedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ota_releases_layer_platform_channel_build_bundle_key`(`layer`(32), `platform`(32), `channel`(16), `buildNumber`, `bundleType`(16), `updateMethod`(32)),
    INDEX `ota_releases_layer_platform_channel_isPublished_buildNumber_idx`(`layer`, `platform`, `channel`, `isPublished`, `buildNumber`),
    INDEX `ota_releases_isPublished_idx`(`isPublished`),
    INDEX `ota_releases_deletedAt_idx`(`deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
